baseURL: "https://awsinsiders.com/"
title: "AWS Insiders"
theme: "PaperMod"

languageCode: "en-us"
defaultContentLanguage: "en"
enableInlineShortcodes: true

pagination:
  pagerSize: 10

params:
  defaultTheme: dark
  disableThemeToggle: false

<<<<<<< HEAD
=======
  assets:
   # customCSS: ["css/custom.css"]

>>>>>>> d54290fcf6964ac3783679ea99ff6567835ad3e7
  homeInfoParams:
    Title: "Welcome to AWS Insiders"
    Content: >
      A curated space for cloud engineers, TAMs, and DevOps pros — powered by real-world AWS experience.

  socialIcons:
<<<<<<< HEAD
    - name: "Github"
      url: "https://github.com/CloudsReign"
      title: "GitHub"
    - name: "Linkedin"
      url: "https://www.linkedin.com/in/chrislutes"
      title: "LinkedIn"
=======
    - name: "GitHub"
      url: "https://github.com/CloudsReign"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/christianlutes"
>>>>>>> d54290fcf6964ac3783679ea99ff6567835ad3e7

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10

<<<<<<< HEAD
    - identifier: daily
      name: Daily Tips
      url: /daily/
      weight: 15

=======
>>>>>>> d54290fcf6964ac3783679ea99ff6567835ad3e7
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 20

    - identifier: tools
      name: Tools & Downloads
      url: /tools/
      weight: 30

ignoreFiles:
  - "\\~"
  - "\\.bak$"
  - "\\.tmp$"
  - "\\.swp$"
<<<<<<< HEAD

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
  section:
    - HTML
  taxonomy:
    - HTML
  term:
    - HTML
=======
>>>>>>> d54290fcf6964ac3783679ea99ff6567835ad3e7
